# Generated by Django 3.2.8 on 2021-10-11 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_category', '0003_auto_20211011_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('image', models.ImageField(upload_to='product_pic/')),
                ('New_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Old_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('stock', models.ImageField(upload_to='')),
                ('status', models.CharField(choices=[('True', True), ('False', False)], max_length=50)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_category.category')),
            ],
        ),
    ]
