# Generated by Django 3.2.8 on 2021-10-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
