# Generated by Django 3.2.8 on 2021-10-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=55, unique=True)),
                ('short_description', models.TextField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('cat_img', models.ImageField(blank=True, upload_to='photos/categories')),
                ('status', models.CharField(choices=[('True', True), ('False', False)], max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
